# Generated by Django 3.2.12 on 2022-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
    ]
